name:                card
version:             0.1.0.0
github:              "MatrixAI/Haskell-Demo"
license:             Apache
author:              "CMCDragonkai"
maintainer:          "roger.qiu@matrix.ai"
copyright:           "Copyright: (c) 2017 Matrix AI"

extra-source-files:
- README.md
- package.yaml

description:         Please see the README on Github at <https://github.com/MatrixAI/Haskell-Demo#readme>

dependencies:
- base >= 4.7 && < 5

system-build-tools:
- hello

library:
  source-dirs: src
  exposed-modules:
    - Card
    - Proj2

executables:
  card-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - card


tests:
  card-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - card
